name: Bump @seatsio/seatsio-types version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version for @seatsio/seatsio-types. Leave empty to use the latest version published on NPM.'
        required: false
        type: string

jobs:
  bump:
    uses: seatsio/seatsio-github-actions/.github/workflows/bump-seatsio-types.yml@v2
    with:
      version: ${{ inputs.version }}
    permissions:
      contents: write
      pull-requests: write
